---
title: "Workout Tracker"
format: dashboard
theme: [sandstone, theme/custom.scss]
fig-width: 10
fig-asp: 0.4
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(readxl)
library(scales)
library(gt)
```

```{r}
#| label: load-data
#| message: false
workout_sheet <- read_excel("data/2025-02-23_Workout_SD.xlsx", sheet = 1)
```

# Home

```{r}
#| label: all-values
#| results: hide

num_workouts <- length(unique(workout_sheet$date))
total_volume <- sum(workout_sheet$weight_lb * workout_sheet$rep)
top_exercise <- workout_sheet |>
      group_by(exercise) |>
      summarise(total_volume = weight_lb * rep) |>
      ungroup() |>
      slice_max(order_by = total_volume) |>
      pull(exercise)
longest_streak <- workout_sheet |>
  mutate(date = as.Date(date), 
         week = floor_date(date, "week")) |>
  distinct(week) |> # Keep unique weeks
  arrange(week) |>
  mutate(gap = c(0, diff(week) == 7),  # Identify gaps of exactly 1 week
         streak_id = cumsum(gap == 0)) |>
  count(streak_id) |>
  summarise(max_streak = max(n)) |>
  pull(max_streak) |>
  paste0(" weeks")

# Muscle type
push = c("Chest", "Triceps", "Shoulders")
pull = c("Back", "Lower back", "Biceps", "Trapezius")
legs = c("Quadriceps", "Hamstrings", "Running")

muscle_type_stat <- function(type) {
  workout_sheet |>
  group_by(muscle_group) |>
  summarise(total_volume = sum(rep*weight_lb), .groups = "drop") |>
  mutate(percent = total_volume / sum(total_volume)) |>
  select(-total_volume) |>
  filter(muscle_group %in% type) |>
  gt() |>
  fmt_percent(
    columns = percent,
    decimals = 1
  ) |>
  cols_label(
    muscle_group = "",
    percent = "Proportion",
    .fn = md
  )
}
```

## Row {height="20%"}

### Column {width="20%"}

```{r}
#| content: valuebox
#| title: "TOTAL WORKOUTS"

list(
  color = "primary",
  value = num_workouts
)
```

### Column {width="20%"}

```{r}
#| content: valuebox
#| title: "TOTAL VOLUME (lbs)"

list(
  color = "warning",
  value = prettyNum(total_volume, big.mark = ", ")
)
```

### Column {width="35%"}

```{r}
#| content: valuebox
#| title: "TOP EXERCISE"

list(
  color = "danger",
  value = top_exercise
)
```

### Column {width="25%"}

```{r}
#| content: valuebox
#| title: "LONGEST STREAK"

list(
  color = "primary",
  value = longest_streak
)
```

## Row {height="35%"}

### Column {width="25%"}

```{r}
#| title: Summary

workout_sheet |>
  filter(muscle_group != "Running") |>
  mutate(main_muscle_group = case_match(
  muscle_group,
  c("Back", "Lower back") ~ "Back",
  c("Biceps", "Triceps", "Forearms", "Shoulders", "Trapezius") ~ "Arms & Shoulders",
  c("Quadriceps", "Hamstrings", "Glutes", "Calves") ~ "Legs",
  "Chest" ~ "Chest",
  "Abdominals" ~ "Abdominals"
  )) |>
  group_by(main_muscle_group) |>
  summarise(total_volume = sum(rep*weight_lb), .groups = "drop") |>
  mutate(percent = total_volume / sum(total_volume)) |>
  select(-total_volume) |>
  gt() |>
  fmt_percent(
    columns = percent,
    decimals = 1
  ) |>
  tab_style(
    style = cell_text(color = "#ae8b2d", weight = "bold"),
    locations = cells_body(
      columns = everything(),
      rows = percent >= .4
    )
  ) |>
    tab_style(
    style = cell_text(color = "#0e2635", weight = "bold"),
    locations = cells_body(
      columns = everything(),
      rows = percent <= .1
    )
  ) |>
  cols_label(
    main_muscle_group = "",
    percent = "Proportion",
    .fn = md
  )
```

### Column {width="25%"}

```{r}
#| title: Push

muscle_type_stat(push)
```

### Column {width="25%"}

```{r}
#| title: Pull

muscle_type_stat(pull)
```

### Column {width="25%"}

```{r}
#| title: Legs

muscle_type_stat(legs)
```

## Row {height="45%"}

```{r}
#| title: Body composition

body_comp_data <- tibble(
  month = LETTERS[1:12],
  Lean = runif(12, min = 0.6, max = 1.0),
  Fat = 1-Lean
)

body_comp_data |>
  pivot_longer(-month, names_to = "type", values_to = "percentage") |>
  ggplot(aes(month, y = percentage, fill = type)) +
  geom_col(color = "white") +
  scale_fill_manual(values = c("#ae8b2d", "#0e2635")) +
  scale_y_continuous(labels = label_percent(),
                     limits = c(0, NA),
                     expand = expansion(mult = c(0, 0.1))) +
  labs(x = NULL, y = NULL, fill = NULL) +
  theme_minimal(base_size = 20) +
  theme(legend.position = "top")
```

```{r}
#| title: Total workout volume

total_workout_volume <- tibble(
  month = LETTERS[1:12],
  volume = runif(12, min = 100000, max = 200000)
)

total_workout_volume |>
  mutate(highest = volume == max(volume)) |>
  ggplot(aes(month, volume / 1000, fill = highest)) +
  geom_col() +
  scale_fill_manual(values = c("#ae8b2d", "#0e2635"), guide = "none") +  # Default & highlight color
  labs(x = NULL, y = "Total volume (lbs)") +
  scale_y_continuous(labels = scales::label_number(suffix = " K"),
                     limits = c(0, NA),
                     expand = expansion(mult = c(0, 0.1))) +
  theme_minimal(base_size = 20)
```

# Workout

```{r}
create_plot <- function(group_name) {
  required_cols <- c("muscle_group", "weight_lb", "rep", "date")
  if (!all(required_cols %in% colnames(workout_sheet))) return(NULL)
  
  muscle_data <- workout_sheet |>
    filter(muscle_group %in% group_name) |>
    mutate(volume = weight_lb * rep) |>
    arrange(date)  # Ensure the data is sorted
  
  # Aggregate total volume by week (Sunday to Saturday)
  muscle_data <- muscle_data |>
    mutate(
      week_start = floor_date(as.Date(date), "week", week_start = 7),  # Start on Sunday
      week_end = week_start + 6,  # End on Saturday
      week_label = paste(format(week_start, "%b %d"), "-", format(week_end, "%b %d"))
    ) |>
    group_by(week_label, week_start) |>
    summarise(total_volume = sum(volume), .groups = "drop") |> # Aggregate weekly
    mutate(highest = total_volume == max(total_volume)) |>
    arrange(week_start) |> 
    slice_tail(n = 10)  # Keep only the last 10 weeks
  
  # Plot the weekly data
  ggplot(muscle_data, aes(x = week_label, y = total_volume/1000, group = 1, fill = highest)) +
    geom_col() +
    scale_y_continuous(labels = scales::label_number(suffix = " K"),
                       limits = c(0, NA),
                       expand = expansion(mult = c(0, 0.1))) +
    labs(x = NULL, y = "Total volume (lbs)") +
    scale_fill_manual(values = c("#ae8b2d", "#0e2635"), guide = "none") +  # Default & highlight color
    theme_minimal(base_size = 20) +
    theme(axis.text.x = element_text(size = 15))
}
```

## Row {height="25%"}

### Column {width="33.33%"}

```{r}
#| title: Chest
#| fig-asp: 0.3
create_plot("Chest")
```

### Column {width="33.33%"}

```{r}
#| title: Biceps
#| fig-asp: 0.3
create_plot("Biceps")
```

### Column {width="33.33%"}

```{r}
#| title: Triceps
#| fig-asp: 0.3
create_plot("Triceps")
```

## Row {height="25%"}

### Column {width="33.33%"}

```{r}
#| title: Hamstrings
#| fig-asp: 0.3
create_plot("Hamstrings")
```

### Column {width="33.33%"}

```{r}
#| title: Quadriceps
#| fig-asp: 0.3
create_plot("Quadriceps")
```

### Column {width="33.33%"}

```{r}
#| title: Back
#| fig-asp: 0.3
create_plot("Back")
```

## Row {height="25%"}

### Column {width="33.33%"}

```{r}
#| title: Lower back
#| fig-asp: 0.3
create_plot("Lower back")
```

### Column {width="33.33%"}

```{r}
#| title: Shoulders
#| fig-asp: 0.3
create_plot("Shoulders")
```

### Column {width="33.33%"}

```{r}
#| title: Trapezius
#| fig-asp: 0.3
create_plot("Trapezius")
```

## Row {height="25%"}

### Column {width="33.33%"}

```{r}
#| title: Abdominals
#| fig-asp: 0.3
create_plot("Abdominals")
```

### Column {width="33.33%"}

```{r}
#| title: Glutes
#| fig-asp: 0.3
create_plot("Glutes")
```

### Column {width="33.33%"}

```{r}
#| title: Calves
#| fig-asp: 0.3
create_plot("Calves")
```
